// Generated by Wrangler by running `wrangler types`

interface Env {
	NEXT_PUBLIC_SITE_URL: string;
	HOLODEX_API_KEY: string;
	NEXT_PUBLIC_REQUEST_URL: string;
	NEXTAUTH_SECRET: string;
	ACCESS_SECRET: string;
	GOOGLE_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	KAKAO_CLIENT_ID: string;
	KAKAO_CLIENT_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	FIREBASE_PROJECT_ID: string;
	FIREBASE_PRIVATE_KEY: string;
	FIREBASE_CLIENT_EMAIL: string;
	NEXT_PUBLIC_FIREBASE_VAPID_KEY: string;
	MONGODB_URI: string;
	ORACLEDB_CONNECTSTRING: string;
	ORACLEDB_PASSWORD: string;
	RATE_LIMITER: RateLimit;
}
